apiVersion: v1
kind: Service
metadata:
  name: gemma-2-9b-it-q4-k-m
  namespace: llama
  labels:
    app: gemma-2-9b-it-q4-k-m
    managed-by: llm-manager
spec:
  type: NodePort
  selector:
    app: gemma-2-9b-it-q4-k-m
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
