apiVersion: v1
kind: Service
metadata:
  name: qwen2-5-coder-14b-instruct-q4-k-m
  namespace: llama
  labels:
    app: qwen2-5-coder-14b-instruct-q4-k-m
    managed-by: llm-manager
spec:
  type: NodePort
  selector:
    app: qwen2-5-coder-14b-instruct-q4-k-m
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
