apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: llama
  labels:
    app: llama-server
spec:
  type: NodePort
  selector:
    app: llama-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
